using System.Net.WebSockets;

namespace Craft.Hosting;

/// <summary>
/// Development-only reverse proxy to the <c>next dev</c> server, so the frontend hot-reloads instead of
/// being served from a precompiled <c>Frontend/</c> directory. Has no effect in production.
/// </summary>
internal static class DevFrontendProxy
{
    private const int PumpBufferBytes = 16 * 1024;

    /// <summary>
    /// Resolves the dev server URL, or <see langword="null"/> when the dev proxy should not run —
    /// which is any node without the Frontend role, and every non-Development environment.
    /// </summary>
    public static string? ResolveDevServerUrl(bool frontendRole, bool isDevelopment, Func<string, string?> env)
    {
        ArgumentNullException.ThrowIfNull(env);

        if (!frontendRole || !isDevelopment) return null;
        return env("CRAFT_DEV_FRONTEND_URL") ?? "http://localhost:3000";
    }

    /// <summary>
    /// Whether a request should go to the dev server rather than the static file middleware.
    /// </summary>
    /// <remarks>
    /// Next.js build output lives under <c>/_next/</c>, and files like <c>/version.json</c> or
    /// <c>/favicon.ico</c> are generated by the dev server rather than existing on disk. API and auth
    /// paths are excluded — those are served by this host, not by Next.
    /// </remarks>
    public static bool ShouldProxy(string path)
    {
        path ??= "";

        if (path.StartsWith("/_next/", StringComparison.Ordinal) ||
            path.StartsWith("/__nextjs", StringComparison.Ordinal))
        {
            return true;
        }

        return Path.HasExtension(path) &&
               !path.StartsWith("/api/", StringComparison.OrdinalIgnoreCase) &&
               !path.StartsWith("/API/", StringComparison.OrdinalIgnoreCase) &&
               !path.StartsWith("/.auth/", StringComparison.OrdinalIgnoreCase);
    }

    /// <summary>
    /// Registers the dev proxy middleware and returns the client the SPA fallback should reuse.
    /// </summary>
    public static HttpClient UseCraftDevFrontendProxy(
        this WebApplication app, string devServerUrl, ILogger logger)
    {
        ArgumentNullException.ThrowIfNull(app);
        ArgumentNullException.ThrowIfNull(devServerUrl);
        ArgumentNullException.ThrowIfNull(logger);

        var client = new HttpClient
        {
            BaseAddress = new Uri(devServerUrl),
            // Generous: a cold Next.js dev build of a large page can take a while.
            Timeout = TimeSpan.FromSeconds(120),
        };

        logger.LogInformation("[System] Dev mode: proxying frontend to {Url}", devServerUrl);

        // Fast Refresh runs over a WebSocket under /_next/*. Without WebSocket support the HTML and
        // asset GETs proxy fine but the HMR socket never establishes, so edits only appear after a
        // manual refresh — which looks like hot-reload being broken rather than missing.
        app.UseWebSockets();
        var devBaseUri = new Uri(devServerUrl);

        app.Use(async (context, next) =>
        {
            var path = context.Request.Path.Value ?? "";

            if (context.WebSockets.IsWebSocketRequest)
            {
                await BridgeWebSocketAsync(context, devBaseUri, path);
                return;
            }

            if (ShouldProxy(path) && await TryProxyAsync(context, client, path)) return;

            await next();
        });

        return client;
    }

    private static async Task BridgeWebSocketAsync(HttpContext context, Uri devBaseUri, string path)
    {
        var scheme = devBaseUri.Scheme == "https" ? "wss" : "ws";
        var target = new Uri($"{scheme}://{devBaseUri.Authority}{path}{context.Request.QueryString}");

        using var upstream = new ClientWebSocket();
        foreach (var protocol in context.WebSockets.WebSocketRequestedProtocols)
            upstream.Options.AddSubProtocol(protocol);

        try
        {
            await upstream.ConnectAsync(target, context.RequestAborted);
        }
        catch (WebSocketException)
        {
            context.Response.StatusCode = 502;
            return;
        }

        using var client = await context.WebSockets.AcceptWebSocketAsync(upstream.SubProtocol);

        await Task.WhenAll(
            PumpAsync(client, upstream, context.RequestAborted),
            PumpAsync(upstream, client, context.RequestAborted));
    }

    /// <summary>Pumps frames one direction between the browser and the dev server.</summary>
    private static async Task PumpAsync(WebSocket from, WebSocket to, CancellationToken ct)
    {
        var buffer = new byte[PumpBufferBytes];
        try
        {
            while (from.State == WebSocketState.Open && to.State == WebSocketState.Open)
            {
                var result = await from.ReceiveAsync(new ArraySegment<byte>(buffer), ct);

                if (result.MessageType == WebSocketMessageType.Close)
                {
                    await to.CloseAsync(WebSocketCloseStatus.NormalClosure, null, ct);
                    break;
                }

                await to.SendAsync(new ArraySegment<byte>(buffer, 0, result.Count),
                    result.MessageType, result.EndOfMessage, ct);
            }
        }
        catch (OperationCanceledException)
        {
            // Browser navigated away or the dev server restarted — both routine.
        }
        catch (WebSocketException)
        {
            // Half-open socket during a dev-server restart; the other pump closes its side.
        }
    }

    /// <returns><see langword="true"/> if the dev server answered and the response is written.</returns>
    private static async Task<bool> TryProxyAsync(HttpContext context, HttpClient client, string path)
    {
        try
        {
            using var proxyRequest = new HttpRequestMessage(
                HttpMethod.Get, path + context.Request.QueryString);

            foreach (var header in context.Request.Headers)
            {
                if (!header.Key.StartsWith("Host", StringComparison.OrdinalIgnoreCase))
                    proxyRequest.Headers.TryAddWithoutValidation(header.Key, header.Value.ToArray());
            }

            using var proxyResponse = await client.SendAsync(
                proxyRequest, HttpCompletionOption.ResponseHeadersRead, context.RequestAborted);

            context.Response.StatusCode = (int)proxyResponse.StatusCode;
            foreach (var header in proxyResponse.Content.Headers)
                context.Response.Headers[header.Key] = header.Value.ToArray();
            foreach (var header in proxyResponse.Headers)
                context.Response.Headers[header.Key] = header.Value.ToArray();

            // ASP.NET applies its own chunking; keeping the upstream value corrupts the response.
            context.Response.Headers.Remove("transfer-encoding");

            await proxyResponse.Content.CopyToAsync(context.Response.Body, context.RequestAborted);
            return true;
        }
        catch (HttpRequestException)
        {
            // Dev server not running — fall through to whatever is on disk.
            return false;
        }
    }
}
